version: "3"
services:
  bot:
    image: lqbing/yoshino
    restart: always
    env_file: .env
    ports: 
      - 8000:8000
    volumes:
      - ./data/bot/log:/workdir/log
      - ./data/bot/yobot_data:/workdir/hoshino/modules/yobot/yobot/src/client/yobot_data
      - ./data/bot/static:/workdir/hoshino/modules/yobot/yobot/src/client/public/static
      - ./data/bot/res:/workdir/res
      - ./data/bot/conf:/root/.hoshino