version: "3"
services:
  miraiok:
    image: lqbing/miraiok
    restart: always
    volumes:
      - ./data/miraok/config.txt:/workdir/config.txt
      - ./data/miraok/setting.yml:/workdir/plugins/CQHTTPMirai/setting.yml
      - ./data/miraok/device.json:/workdir/device.json
      - ./data/miraok/log:/workdir/log
      - ./data/miraok/tmp:/tmp
    stdin_open: true
    tty: true
    networks:
      - bot_net
      
  bot:
    image: lqbing/yoshino
    restart: always
    env_file: .env
    ports: 
      - 8000:8000
    volumes:
      - ./data/bot/log:/workdir/log
      - ./data/bot/yobot_data:/workdir/hoshino/modules/yobot/yobot/src/client/yobot_data
      - ./data/bot/static:/workdir/hoshino/modules/yobot/yobot/src/client/public/static/
      - ./data/bot/res:/workdir/res
    networks:
      - bot_net

networks:
  bot_net:
    driver: bridge
